spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true


logging:
  pattern:
    console: "%d - %msg%n"
#  path: D:\Project\imooc\logs\
  file: D:\Project\imooc\logs\sell.log\

