spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
#confitg the return value not null
#  jackson:
#    default-property-inclusion: not_null
#confitg the controller url path
server:
  servlet:
    context-path: /sell
